name: 'Shellcheck'

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - '**ani-track.sh'

jobs:
  shellcheck:
    name: Lint Shell Scripts
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: List files
      run: ls -l

    - name: Ensure script is executable
      run: |
        chmod +x "./ani-track.sh"

    - name: Run ShellCheck on myscript.sh
      run: |
        sudo apt-get install shellcheck
        shellcheck "./ani-track.sh"
